version: '3.8'

services:
  # POSTGRESQL
  postgres:
    image: postgres:15
    container_name: delivery-postgres
    environment:
      POSTGRES_DB: deliverydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Haikyuu1212
    networks:
      - delivery-network  
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d deliverydb"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  # MONGODB
  mongo:
    image: mongo:7
    container_name: delivery-mongo
    networks:
      - delivery-network
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  # ZOOKEEPER
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: delivery-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - delivery-network  
    ports:
      - "2181:2181"

  # KAFKA
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: delivery-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - delivery-network  
networks:
  delivery-network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: